<?php
/**
 * Created by PhpStorm.
 * User: debasis
 * Date: 16/6/15
 * Time: 12:04 AM
 */

header('Content-type: text/html');
header('Access-Control-Allow-Origin: '.CUSTOM_URL);  //I have also tried the * wildcard and get the same response
header("Access-Control-Allow-Credentials: true");
header('Access-Control-Allow-Methods: GET, PUT, POST, DELETE, OPTIONS');
header('Access-Control-Max-Age: 1000');
header('Access-Control-Allow-Headers: Content-Type, Content-Range, Content-Disposition, Content-Description');


function order_init() // init function called by defaulted when this module loaded by system
{

    //echo $GLOBALS['theme'];
    //echo 5656;
    //echo user_authenticate('debasis','Pp@ss1234');

//echo "kl";
    header('Content-type: text/html');
    header('Access-Control-Allow-Origin: '.CUSTOM_URL);  //I have also tried the * wildcard and get the same response
    header("Access-Control-Allow-Credentials: true");
    header('Access-Control-Allow-Methods: GET, PUT, POST, DELETE, OPTIONS');
    header('Access-Control-Max-Age: 1000');
    header('Access-Control-Allow-Headers: Content-Type, Content-Range, Content-Disposition, Content-Description');



}

function order_menu()
{
    $items = array();

    $items['addorder'] = array(
        'title' => 'Add order',
        'page callback' => 'addorder',
        'access callback' => TRUE,
        'access arguments' => array('Anonymous Actions.'),
        'expanded' => TRUE,
        //'type'=>MENU_NORMAL_ITEM,
    );
    $items['orderlist'] = array(
        'title' => 'order List',
        'page callback' => 'orderlist',
        'access callback' => TRUE,
        'access arguments' => array('Anonymous Actions.'),
        'expanded' => TRUE,
        //'type'=>MENU_NORMAL_ITEM,
    );
    $items['parentorderlist'] = array(
        'title' => 'parent order List',
        'page callback' => 'parentorderlist',
        'access callback' => TRUE,
        'access arguments' => array('Anonymous Actions.'),
        'expanded' => TRUE,
        //'type'=>MENU_NORMAL_ITEM,
    );

    $items['deleteorder'] = array(
        'title' => 'order Delete',
        'page callback' => 'deleteorder',
        'access callback' => TRUE,
        'access arguments' => array('Anonymous Actions.'),
        'expanded' => TRUE,
        //'type'=>MENU_NORMAL_ITEM,
    );
   $items['orderdetails'] = array(
        'title' => 'order details',
        'page callback' => 'orderdetails',
        'access callback' => TRUE,
        'access arguments' => array('Anonymous Actions.'),
        'expanded' => TRUE,
        //'type'=>MENU_NORMAL_ITEM,
    );
    $items['orderupdates'] = array(
        'title' => 'order Updates',
        'page callback' => 'orderupdates',
        'access callback' => TRUE,
        'access arguments' => array('Anonymous Actions.'),
        'expanded' => TRUE,
        //'type'=>MENU_NORMAL_ITEM,
    );

    $items['orderupdatestatus'] = array(
        'title' => 'order Updates Status',
        'page callback' => 'orderupdatestatus',
        'access callback' => TRUE,
        'access arguments' => array('Anonymous Actions.'),
        'expanded' => TRUE,
        //'type'=>MENU_NORMAL_ITEM,
    );
    $items['uploadorderimage'] = array(
        'title' => 'order Image Upload',
        'page callback' => 'uploadorderimage',
        'access callback' => TRUE,
        'access arguments' => array('Anonymous Actions.'),
        'expanded' => TRUE,
        //'type'=>MENU_NORMAL_ITEM,
    );




    return $items;
}

function orderdetails(){
    header('Content-type: text/html');
    header('Access-Control-Allow-Origin: '.CUSTOM_URL);  //I have also tried the * wildcard and get the same response
    header("Access-Control-Allow-Credentials: true");
    header('Access-Control-Allow-Methods: GET, PUT, POST, DELETE, OPTIONS');
    header('Access-Control-Max-Age: 1000');
    header('Access-Control-Allow-Headers: Content-Type, Content-Range, Content-Disposition, Content-Description');
    //echo $_POST['orderid'];
    if(isset($_POST['orderid']) && $_POST['orderid']>0){
        $order_id=$_POST['orderid'];
    }
    $orderquery = db_select('order_details','od');
    $orderquery->leftjoin('admin', 'ad', 'ad.user_id = od.affiliate_id');
    $orderquery->join('country', 'bc', 'bc.id = od.bill_country');
    $orderquery->join('country', 'sc', 'sc.id = od.ship_country');
    $orderquery->join('state', 'bs', 'bs.id = od.bill_state');
    $orderquery->join('state', 'ss', 'ss.id = od.ship_state');
    $orderquery->fields('od');
    $orderquery->fields('ad',array('fname','lname'));
    $orderquery->addExpression("bc.s_name", 'bill_country');
    $orderquery->addExpression("sc.s_name", 'ship_country');
    $orderquery->addExpression("bs.s_st_name", 'bill_state');
    $orderquery->addExpression("ss.s_st_name", 'ship_state');

    $orderquery->condition('od.id', intval($order_id), '=');
    $orderqueryre = $orderquery->execute();
    $orderrecordu_arr = $orderqueryre->fetchAssoc();
    $orderrecordu_arr['order_status1']='Pending';
    if($orderrecordu_arr['order_status']==1){
        $orderrecordu_arr['order_status1']='Pending';
    }
    if($orderrecordu_arr['order_status']==2){
        $orderrecordu_arr['order_status1']='In Progress';
    }

    if($orderrecordu_arr['order_status']==3){
        $orderrecordu_arr['order_status1']='Confirmed';
    }

    if($orderrecordu_arr['order_status']==4){
        $orderrecordu_arr['order_status1']='Canceled';
    }
    if($orderrecordu_arr['fname']!='' && $orderrecordu_arr['lname']!='' ){
        $orderrecordu_arr['affiliate_name']=$orderrecordu_arr['fname'].' '.$orderrecordu_arr['lname'];
    }

    $orderrecordu_arr['order_date']=date('d/m/Y',$orderrecordu_arr['order_time']);
    $orderrecordu_arr['order_timee']=$invoicedate=date('jS F, Y',$orderrecordu_arr['order_time']);
    $orderproductquery = db_select('order_product_details','opd');
    $orderproductquery->fields('opd');
    $orderproductquery->condition('order_id', intval($order_id), '=');
    $orderproqueryre = $orderproductquery->execute();
    $orderlist=array();
    if ($orderproqueryre->rowCount() > 0) {
        $i = 0;

        $productsubtotal = 0.00;
        while ($recorduorderpro = $orderproqueryre->fetchAssoc()) {
            $temparray = $recorduorderpro;
            $temparray['product_subtotal']=floatval($recorduorderpro['quantity']*$recorduorderpro['product_price']);
            $orderlist[$i]= $temparray;
            $i++;
        }
    }
        $orderrecordu_arr['productdet']=$orderlist;







        echo json_encode(@$orderrecordu_arr);
}


function orderlist()
{
    header('Content-type: text/html');
    header('Access-Control-Allow-Origin: '.CUSTOM_URL);  //I have also tried the * wildcard and get the same response
    header("Access-Control-Allow-Credentials: true");
    header('Access-Control-Allow-Methods: GET, PUT, POST, DELETE, OPTIONS');
    header('Access-Control-Max-Age: 1000');
    header('Access-Control-Allow-Headers: Content-Type, Content-Range, Content-Disposition, Content-Description');

    $orderlist = array();


    $queryu = db_select('order_details', 'o');
    $queryu->join('admin', 'a', 'a.user_id = o.user_id');
    $queryu->fields('o');
    $queryu->fields('a', array('fname', 'lname'));
    if(isset($_POST['userid']) && $_POST['userid']>0){
        $queryu->condition('o.user_id',$_POST['userid'],'=')  ;
    }
    if(isset($_POST['affiliateid']) && $_POST['affiliateid']>0){
        $queryu->condition('o.affiliate_id',$_POST['affiliateid'],'=')  ;
    }


 /*   if(isset($_POST['type']) && $_POST['type']!=''){
        $queryu->condition('ca.type',$_POST['type'],'=')  ;
    }*/
    $queryu->orderBy('o.order_time','desc');

      $resultu = $queryu->execute();


    if ($resultu->rowCount() > 0) {
        $i = 0;
        while ($recordu = $resultu->fetchAssoc()) {
            $temparray=$recordu;
            if($recordu['affiliate_id']!=0){
                $queryaffi = db_select('admin', 'ad');
                $queryaffi->fields('ad', array('fname', 'lname'))
                ->condition('ad.user_id', $recordu['affiliate_id'], '=');
                $resultuaffi = $queryaffi->execute();
                if ($resultuaffi->rowCount() > 0) {

                    while ($recorduaffi = $resultuaffi->fetchAssoc()) {
                        $affiliatename= $recorduaffi['fname'].' '.$recorduaffi['lname'];



                        $temparray['affiliatename']=$affiliatename;
                    }
                }

            }
            if($recordu['fname']!='' && $recordu['fname']!=''){
                $temparray['orderby']=$recordu['fname'].' '.$recordu['lname'];
            }

            if($recordu['order_time']!=''){
                $temparray['orderdate']=date('d F Y H:i:s',$recordu['order_time']);
            }
            $recordu['order_status1']='Pending';
            if($recordu['order_status']==1){
                $temparray['order_status1']='Pending';
            }
            if($recordu['order_status']==2){
                $temparray['order_status1']='In Progress';
            }

            if($recordu['order_status']==3){
                $temparray['order_status1']='Confirmed';
            }

            if($recordu['order_status']==4){
                $temparray['order_status1']='Canceled';
            }
            $temparray['dd_order_status']['id']=intval($recordu['order_status']);
            $orderlist[$i]= $temparray;
            $i++;


        }
}
     // $records['user']=$userlist;




    echo json_encode(@$orderlist);



}

function addorder(){

    header('Content-type: text/html');
    header('Access-Control-Allow-Origin: '.CUSTOM_URL);  //I have also tried the * wildcard and get the same response
    header("Access-Control-Allow-Credentials: true");
    header('Access-Control-Allow-Methods: GET, PUT, POST, DELETE, OPTIONS');
    header('Access-Control-Max-Age: 1000');
    header('Access-Control-Allow-Headers: Content-Type, Content-Range, Content-Disposition, Content-Description');
    $parent_cat=0;
    $cat_image='';
    if(isset($_POST['parent_cat']) && $_POST['parent_cat']>0){
        $parent_cat=$_POST['parent_cat']['id'];
    }
    if(isset($_POST['cat_image']) && $_POST['cat_image']!=''){
        $cat_image=$_POST['cat_image'];
    }

    $query = db_insert('order')->fields(array('cat_name','cat_desc','parent_cat','cat_image','status','priority'));
        //foreach ($values as $record) {
        $query->values(array(@$_POST['cat_name'],@$_POST['cat_desc'],@$parent_cat,$cat_image,1,@$_POST['priority']));
        //}
        $query->execute();


    $data['status'] = 'success';
     echo json_encode($data);
    return;
}
function orderupdates(){

    header('Content-type: text/html');
    header('Access-Control-Allow-Origin: '.CUSTOM_URL);  //I have also tried the * wildcard and get the same response
    header("Access-Control-Allow-Credentials: true");
    header('Access-Control-Allow-Methods: GET, PUT, POST, DELETE, OPTIONS');
    header('Access-Control-Max-Age: 1000');
    header('Access-Control-Allow-Headers: Content-Type, Content-Range, Content-Disposition, Content-Description');
    db_update('order')
        ->fields(array('cat_name'=>@$_POST['cat_name'],'cat_desc'=>@$_POST['cat_desc'],'parent_cat'=>@$_POST['parent_cat']['id'],'cat_image'=>@$_POST['cat_image'],'priority'=>@$_POST['priority']))
        ->condition('id', intval($_POST['id']))
         ->execute();
}



function deleteorder(){

    header('Content-type: text/html');
    header('Access-Control-Allow-Origin: '.CUSTOM_URL);  //I have also tried the * wildcard and get the same response
    header("Access-Control-Allow-Credentials: true");
    header('Access-Control-Allow-Methods: GET, PUT, POST, DELETE, OPTIONS');
    header('Access-Control-Max-Age: 1000');
    header('Access-Control-Allow-Headers: Content-Type, Content-Range, Content-Disposition, Content-Description');
    $num_deleted = db_delete('order')
        ->condition('id', @$_POST['id'])
        ->execute();

}

function orderupdatestatus(){

    header('Content-type: text/html');
    header('Access-Control-Allow-Origin: '.CUSTOM_URL);  //I have also tried the * wildcard and get the same response
    header("Access-Control-Allow-Credentials: true");
    header('Access-Control-Allow-Methods: GET, PUT, POST, DELETE, OPTIONS');
    header('Access-Control-Max-Age: 1000');
    header('Access-Control-Allow-Headers: Content-Type, Content-Range, Content-Disposition, Content-Description');
    $status=intval($_POST['status']['id']);
    $query=db_update('order_details')
        ->fields(array('order_status'=>@$status))
        ->condition('id', intval($_POST['id']))
        ->execute();

    echo "true";
}




